services:
  baidu-autosave:
    image: kokojacket/baidu-autosave:latest
    container_name: baidu-autosave
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./log:/app/log
      - ./state:/app/state
    environment:
      TZ: Asia/Shanghai
